[versions]
commons-cli = '1.11.0'
commons-codec = '1.20.0'
commons-collections4 = '4.5.0'
commons-compress = '1.28.0'
commons-csv = '1.14.1'
commons-exec = '1.5.0'
commons-io = '2.21.0'
commons-lang3 = '3.20.0'
commons-pool2 = '2.12.1'
commons-text = '1.14.0'

jakarta-annotation-api = '3.0.0'
jakarta-persistence-api = '3.2.0'
jakarta-validation-api = '3.1.1'
jakarta-xml-bind-api = '4.0.4'

caffeine = '3.2.3'
febit-devkit = '1.4.2'
hierynomus-license = '0.16.1'
jackson = '2.20.1'
jcommander = '3.0'
jool = '0.9.15'
jooq = '3.19.28'
jsonpath = '2.10.0'
jsr305 = '3.0.2'
kafka-clients = '4.1.1'
nimbus-jose-jwt = '10.6'
slf4j = '2.0.17'
snakeyaml = '2.5'
spotbugs = '4.9.8'
spring = '6.2.14'
swagger = '2.2.41'
uuid-generator = '5.1.1'

assertj = '3.27.6'
hamcrest = '3.0'
junit = '5.14.1'
mockito = '5.20.0'


[plugins]
febit-bom = { id = 'org.febit.standard-bom', version.ref = 'febit-devkit' }
febit-codegen-module = { id = 'org.febit.codegen-module', version.ref = 'febit-devkit' }
febit-java = { id = 'org.febit.standard-java', version.ref = 'febit-devkit' }
febit-maven-publish = { id = 'org.febit.standard-maven-publish', version.ref = 'febit-devkit' }
license = { id = 'com.github.hierynomus.license', version.ref = 'hierynomus-license' }


[libraries]
assertj-bom = { module = 'org.assertj:assertj-bom', version.ref = 'assertj' }
jackson-bom = { module = 'com.fasterxml.jackson:jackson-bom', version.ref = 'jackson' }
junit-bom = { module = 'org.junit:junit-bom', version.ref = 'junit' }
mockito-bom = { module = 'org.mockito:mockito-bom', version.ref = 'mockito' }

jakarta-annotation-api = { module = 'jakarta.annotation:jakarta.annotation-api', version.ref = 'jakarta-annotation-api' }
jakarta-persistence-api = { module = 'jakarta.persistence:jakarta.persistence-api', version.ref = 'jakarta-persistence-api' }
jakarta-validation-api = { module = 'jakarta.validation:jakarta.validation-api', version.ref = 'jakarta-validation-api' }
jakarta-xml-bind-api = { module = 'jakarta.xml.bind:jakarta.xml.bind-api', version.ref = 'jakarta-xml-bind-api' }

commons-cli = { module = 'commons-cli:commons-cli', version.ref = 'commons-cli' }
commons-codec = { module = 'commons-codec:commons-codec', version.ref = 'commons-codec' }
commons-collections4 = { module = 'org.apache.commons:commons-collections4', version.ref = 'commons-collections4' }
commons-compress = { module = 'org.apache.commons:commons-compress', version.ref = 'commons-compress' }
commons-csv = { module = 'org.apache.commons:commons-csv', version.ref = 'commons-csv' }
commons-exec = { module = 'org.apache.commons:commons-exec', version.ref = 'commons-exec' }
commons-io = { module = 'commons-io:commons-io', version.ref = 'commons-io' }
commons-lang3 = { module = 'org.apache.commons:commons-lang3', version.ref = 'commons-lang3' }
commons-pool2 = { module = 'org.apache.commons:commons-pool2', version.ref = 'commons-pool2' }
commons-text = { module = 'org.apache.commons:commons-text', version.ref = 'commons-text' }

caffeine = { module = 'com.github.ben-manes.caffeine:caffeine', version.ref = 'caffeine' }
hamcrest = { module = 'org.hamcrest:hamcrest', version.ref = 'hamcrest' }
jcommander = { module = 'org.jcommander:jcommander', version.ref = 'jcommander' }
jool = { module = 'org.jooq:jool', version.ref = 'jool' }
jooq = { module = 'org.jooq:jooq', version.ref = 'jooq' }
jsonpath = { module = 'com.jayway.jsonpath:json-path', version.ref = 'jsonpath' }
jsr305 = { module = 'com.google.code.findbugs:jsr305', version.ref = 'jsr305' }
kafka-clients = { module = 'org.apache.kafka:kafka-clients', version.ref = 'kafka-clients' }
nimbus-jose-jwt = { module = 'com.nimbusds:nimbus-jose-jwt', version.ref = 'nimbus-jose-jwt' }
snakeyaml = { module = 'org.yaml:snakeyaml', version.ref = 'snakeyaml' }
sping-core = { module = 'org.springframework:spring-core', version.ref = 'spring' }
sping-web = { module = 'org.springframework:spring-web', version.ref = 'spring' }
spotbugs-annotations = { module = 'com.github.spotbugs:spotbugs-annotations', version.ref = 'spotbugs' }
swagger-annotations = { module = 'io.swagger.core.v3:swagger-annotations', version.ref = 'swagger' }
uuid-generator = { module = 'com.fasterxml.uuid:java-uuid-generator', version.ref = 'uuid-generator' }
